version: "3.3"
services:
  proxy:
    build: proxy/
    image: proxy
    container_name: proxy
    networks:
      - honet
    ports:
      - target: 8080
        published: 6969
        protocol: tcp
        mode: host
  realapp:
    build: realapp/
    image: realapp
    container_name: realapp
    networks:
      - honet
    depends_on:
      - proxy
  fakeapp:
    build: fakeapp/
    image: fakeapp
    container_name: fakeapp
    networks:
      - honet
    depends_on:
      - proxy
networks:
  honet: